### ISSUE TITLE
Issues in /admin

### ISSUE THREAD

**Issue by iamdarkle** [Genaker/Luma-React-PWA-Magento-Theme#1]
I am really impressed with what you have achieved, the theme is incredibly fast, unfortunately I am experiencing a problem in /admin with these console errors: 

![Screenshot 2022-03-31 031204](https://user-images.githubusercontent.com/15818451/160957299-578082ed-d7d3-478a-a299-4f3d88765806.png)

I noticed it when trying to modify the data of a product that jumps an error message that doesn't allow you to save the data.

I really hope you keep working on this, your project must gain popularity because it deserves it, I'm especially looking forward to the release in two weeks time of 2.4.4 which incorporates quite a few performance improvements with php 8.1, which combined with this has to be amazing!

**Comment by Genaker** [comment]
It is not a Theme issue. The theme doesn't change  Admin in any way. It is Magento 2 it is broken and errors it is normal.

**Comment by iamdarkle** [comment]
Ah ok in that case sorry for the inconvenience, thanks, I'm closing this.

**Comment by Genaker** [comment]
Thank you very much for letting me know about this issue. If you have any
issues or questions please feel free to submit ticket.
