### ISSUE TITLE
SOS I destroyed my site with your theme! Cannot login to admin!

### ISSUE THREAD

**Issue by cptX** [Genaker/Luma-React-PWA-Magento-Theme#2]
Hi, please help me. After installing your theme something broke and I cannot login back to admin.
I receive the following error

`Error: Cannot use object of type Magento\Framework\View\Asset\Merged as array in /var/www/magento/vendor/genaker/magento-reactjs/React/React/ReactInjectPlugin.php:81
Stack trace:
#0 /var/www/magento/vendor/magento/framework/View/Page/Config/Renderer.php(297): React\React\ReactInjectPlugin->renderAssetHtml()
#1 /var/www/magento/vendor/magento/framework/View/Page/Config/Renderer.php(284): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup()
#2 /var/www/magento/vendor/magento/framework/View/Page/Config/Renderer.php(137): Magento\Framework\View\Page\Config\Renderer->renderAssets()
#3 /var/www/magento/vendor/magento/framework/View/Result/Page.php(252): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#4 /var/www/magento/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#5 /var/www/magento/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(140): Magento\Framework\View\Result\Layout->renderResult()
#6 /var/www/magento/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#7 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#8 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#9 /var/www/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#10 {main}`

I went to database and set design/theme/theme_id to null in order to trigger the usage of the default luma  but didn't succeed!

What can I do to restore default LUMA and then we will see what went wrong with your theme?

**Comment by cptX** [comment]
Finally I got out of the situation by uninstalling your theme.
When discovered your theme I was excited but I didn't manage to succeed running it. Magento was throwing errors that didn't find React and Vue...
Is it compatible with Magento 2.4.5?

**Comment by cptX** [comment]
Tried once more to reinstall it and got the same error as above when trying to get in the admin page

**Comment by Genaker** [comment]
Probably it doesn't work with Magento 2.4.5. Magento …!

**Comment by cptX** [comment]
Please can you explain more? I lost several hours yesterday with this issue. Can you please explain with which versions is your theme compatible? And how could we make it compatible with 2.4.5?

**Comment by Genaker** [comment]
To make it compatible you need to fix the error you reported.

**Comment by Genaker** [comment]
> Finally I got out of the situation by uninstalling your theme.
> 
> When discovered your theme I was excited but I didn't manage to succeed running it. Magento was throwing errors that didn't find React and Vue...
> 
> Is it compatible with Magento 2.4.5?

I checked it with v 2.4.5-p4 everything is working 

![image](https://github.com/user-attachments/assets/6ff21ae0-d7ec-4cf5-a485-371521601d3b)
