### ISSUE TITLE
Getting issue related to requirejs after enabling theme on magento 2.4.5

### ISSUE THREAD

**Issue by gulshanchitransh-se** [Genaker/Luma-React-PWA-Magento-Theme#4]
I have enabled react-luma theme on magento 2.4.5 and all the js stopped working.

Uncaught TypeError: require.config is not a function
Uncaught ReferenceError: define is not defined

Please check attached screenshot:

![Screenshot 2024-02-06 150554](https://github.com/Genaker/Luma-React-PWA-Magento-Theme/assets/158168295/99963a46-9b31-4232-a6fb-a7a42731a2df)

@Genaker Please let me know on which magento version this theme works

**Comment by Genaker** [comment]
Correct! Magento JS must stop. It doesn't use magento JS.

**Comment by gulshanchitransh-se** [comment]
Previously it was showing lots of error like requirejs. So is it fixed now @Genaker ?

**Comment by Genaker** [comment]
It will show errors. It is the default magento JS. But it doesn't affect
the idea. I have the version with these issues somewhere. However, it
doesn't matter if you are building your theme removing this code anyway

**Comment by gulshanchitransh-se** [comment]
ok thanks for the information.

**Comment by Genaker** [comment]
If you really need this, I can fix it. However it doesn't affect the
functionality of the theme. It is just old Magento code. Anyway you need
implement your own JS if you need something

**Comment by gulshanchitransh-se** [comment]
I just wanted to remove unnecessary magento js which makes website slow.

**Comment by Genaker** [comment]
Yes, it removes. That's why it has an error. You need to run regexp to
remove the rest of the magento JS, which does not execute anyway.

**Comment by gulshanchitransh-se** [comment]
ok I will test it again and let you know if any help required.

**Comment by Genaker** [comment]
To remove Magento 2 Js, you do not need a theme but just this extension.

https://github.com/Genaker/reactmagento2

Install the extension and disable the JS
